name: Test
on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - run: make install
      - run: |
          gh associated-pr ${{ github.ref }}
      - run: |
          gh associated-pr ${{ github.sha }}
      - run: |
          gh associated-pr --graphql ${{ github.sha }}
      - run: |
          gh associated-pr --search ${{ github.sha }}
      - run: |
          gh associated-pr --pr-list ${{ github.sha }}
      - run: |
          gh associated-pr --pr-list ${{ github.sha }}
